export const mockOrder = {
  id: "fake-order-id",
  orderNumber: "US_FAKE_ORDER_NUMBER",
  customerEmail: "paddingtonbear6335@gmail.com",
  customerId: "test-customer-id",
  shipmentStatus: "Shipped",
  createdAt: "2024-03-05T05:54:45.077Z",
  totalPrice: 3900,
  totalNet: 3250,
  totalTax: 650,
  billingAddress: {
    firstName: "Jane",
    lastName: "Doe",
    addressLine1: "123 Mayfair Ave Apt 55A",
    addressLine2: "",
    city: "Alameda",
    state: "CA",
    postalCode: "02145",
    countryCode: "US",
  },
  shippingAddress: {
    firstName: "Jane",
    lastName: "Doe",
    addressLine1: "123 Mayfair Ave Apt 55A",
    addressLine2: "",
    city: "Alameda",
    state: "CA",
    postalCode: "02145",
    countryCode: "US",
  },
  shippingMethod: "USPS",
  version: 1,
  currencyCode: "GBP",
  lineItems: [
    {
      product: {
        id: "mock-product-id",
        sku: "mock-product-sku",
        attributes: {
          orderOrigin: "mock-order-origin",
          returnableDays: 14,
          frequency: 2,
        },
      },
      name: "Fake Line Item!",
      price: 9999,
      quantity: 1,
    },
  ],
};
