const avataxTransactionObj = {
  currencyCode: "USD",
  exchangeRateCurrencyCode: "USD",
  locationCode: "",
  reportingLocationCode: "",
  purchaseOrderNo: "2024-06-17",
  referenceCode: "",
  salespersonCode: "",
  totalAmount: 120,
  totalExempt: 120,
  totalDiscount: 0,
  totalTax: 0,
  totalTaxable: 0,
  totalTaxCalculated: 0,
  adjustmentReason: "NotAdjusted",
  locked: false,
  version: 1,
  exchangeRateEffectiveDate: "2024-06-17",
  exchangeRate: 1,
  description: "Sensor",
  modifiedDate: "2024-06-17T18:39:23.6416046Z",
  modifiedUserId: 6601551,
  taxDate: "2024-06-17",
  lines: [
    {
      id: 0,
      transactionId: 0,
      lineNumber: "1",
      customerUsageType: "",
      entityUseCode: "",
      description: "Sensor",
      discountAmount: 0,
      exemptAmount: 120,
      exemptCertId: 0,
      exemptNo: "",
      isItemTaxable: false,
      itemCode: "USLG02BS",
      lineAmount: 120,
      quantity: 1,
      ref1: "",
      ref2: "",
      reportingDate: "2024-06-17",
      sourcing: "Destination",
      tax: 0,
      taxableAmount: 0,
      taxCalculated: 0,
      taxCode: "SI010004",
      taxCodeId: 40140,
      taxDate: "2024-06-17",
      taxIncluded: false,
      details: [Array],
      nonPassthroughDetails: [],
      hsCode: "",
      costInsuranceFreight: 0,
      vatCode: "",
      vatNumberTypeId: 0,
    },
  ],
  addresses: [
    {
      id: 0,
      transactionId: 0,
      boundaryLevel: "Address",
      line1: "2823 Baker St",
      line2: "",
      line3: "",
      city: "San Francisco",
      region: "CA",
      postalCode: "94123",
      country: "US",
      taxRegionId: 4016940,
      latitude: "37.797077",
      longitude: "-122.445775",
    },
    {
      id: 0,
      transactionId: 0,
      boundaryLevel: "Address",
      line1: "3303 E Holmes Rd",
      line2: "",
      line3: "",
      city: "Memphis",
      region: "TN",
      postalCode: "38118",
      country: "US",
      taxRegionId: 4013855,
      latitude: "35.006099",
      longitude: "-89.953119",
    },
  ],
  summary: [
    {
      country: "US",
      region: "CA",
      jurisType: "State",
      jurisCode: "06",
      jurisName: "CALIFORNIA",
      taxAuthorityType: 45,
      stateAssignedNo: "",
      taxType: "Use",
      taxSubType: "U",
      taxName: "CA STATE TAX",
      rateType: "General",
      taxable: 0,
      rate: 0,
      tax: 0,
      taxCalculated: 0,
      nonTaxable: 120,
      exemption: 0,
    },
  ],
  apStatusCode: null,
  apStatus: null,
};
export default avataxTransactionObj;
