name: build push release
run-name: ${{ github.event_name == 'push' && format('(release) {0}', github.event.head_commit.message) || format('({0}) Building {1}', inputs.build_env, github.sha) }}

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

  workflow_dispatch:
    inputs:
      build_env:
        description: "Which environment? [staging, production]"
        default: "staging"
        type: "choice"
        options:
          - staging
          - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'push' && 'release' || github.event.inputs.build_env }}
  cancel-in-progress: true

jobs:
  build-push-release:
    uses: ./.github/workflows/build-push.yaml
    with:
      BUILD_TYPE: "release"
      BUILD_ENV: ${{ github.event_name == 'push' && 'staging' || github.event.inputs.build_env }}
    secrets: inherit

  build-push-prod:
    uses: ./.github/workflows/build-push.yaml
    if: github.event_name == 'push'
    with:
      BUILD_TYPE: "release"
      BUILD_ENV: "production"
    secrets: inherit
